name: Test plot
on:
  push:
    branches: [ master ]
  pull_request_target:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.8", "3.9","3.10"]
    
    defaults:
      run:
        shell: "bash -l {0}"

    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v2
      with:
        cvmfs_repositories: 'grid.cern.ch'

    - name: Set conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        auto-update-conda: true
        activate-environment: CoffeaRunner
        environment-file: env.yml
        auto-activate-base: false

    - name: Verify environment
      run: |
        conda info
        conda env list
        conda list
        
      
    - name: Install Repo
      run: |
        pip install -e .

    
    - name: data/MC plotter		
      run: |
        python plotting/plotdataMC.py --cfg testfile/btv_datamc.yml 
    
    - name: comparison plotter 
      run: |
        python plotting/comparison.py --cfg testfile/btv_comapre.yml 